name: SKL CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  CI:
    runs-on: ubuntu-22.04

    env:
      SKL_TAG: v3.0.0
      TOOLCHAIN_TAG: 2025.08.28

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set CPU core count
      run: echo "NPROC=$(nproc)" >> $GITHUB_ENV

    - name: Check license headers
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        HEAD_SHA=${{ github.event.pull_request.head.sha }}
        BASE_SHA=${{ github.event.pull_request.base.sha }}
        MERGE_BASE_SHA=$(git merge-base $HEAD_SHA $BASE_SHA)
        git diff --name-only $MERGE_BASE_SHA $HEAD_SHA | xargs ./.github/check_license_headers.py

    - name: Setup QEMU
      run: |
        gh release download $SKL_TAG -p "$QEMU_TARBALL"
        tar -xvf $QEMU_TARBALL
        echo "${{ github.workspace }}" >> $GITHUB_PATH
      env:
        QEMU_TARBALL: qemu-riscv64-v10.1.0-ubuntu-22.04.tar.xz
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup toolchain
      run: |
        gh release download $TOOLCHAIN_TAG -R riscv-collab/riscv-gnu-toolchain -p "$TOOLCHAIN_TARBALL"
        tar -xvf $TOOLCHAIN_TARBALL
        echo "${{ github.workspace }}/riscv/bin" >> $GITHUB_PATH
      env:
        TOOLCHAIN_TARBALL: riscv64-elf-ubuntu-22.04-llvm-nightly-${{ env.TOOLCHAIN_TAG }}-nightly.tar.xz
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup clang-tidy
      run: |
        gh release download $SKL_TAG -p "$CLANG_TIDY_TARBALL"
        tar -xvf $CLANG_TIDY_TARBALL -C ${{ github.workspace }}/riscv/bin
      env:
        CLANG_TIDY_TARBALL: riscv64-unknown-elf-clang-tidy.tar.xz
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: clang-format
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        HEAD_SHA=${{ github.event.pull_request.head.sha }}
        BASE_SHA=${{ github.event.pull_request.base.sha }}
        MERGE_BASE_SHA=$(git merge-base $HEAD_SHA $BASE_SHA)
        git diff --name-only --diff-filter=ACMR $MERGE_BASE_SHA $HEAD_SHA "*.[ch]"| \
          xargs clang-format --dry-run --Werror

    - name: CMake configure and build
      run: |
        echo "Using $NPROC threads for build step"
        cmake -B ${{ github.workspace }}/build \
              -DCMAKE_TOOLCHAIN_FILE=cmake/riscv.cmake \
              -DSKL_ENABLE_BENCHMARKS=ON \
              -DSKL_ENABLE_TESTS=ON
        cmake --build ${{ github.workspace }}/build --verbose --parallel $NPROC

    - name: CTest
      working-directory: ${{ github.workspace }}/build
      run: ctest --output-on-failure --parallel $NPROC
